version: '3'
services:
  django:
    build: ./app
    volumes:
      - ./app:/project
    ports:
      - 8081:8000

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./app/media:/usr/share/nginx/media
    ports:
      - "8006:8080"
  